### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by JohnnyX071** [DaPigGuy/PiggyCrates#100]
If I want to make a crate that gives the players an ore spawner or a minon. That would be done by executing the command /orespawner {player} {type} or /minion {player} {type} but I have to put an item that will be seen on the crate so when a player gets it he will both get the item from the command and the Item that is added to be displayed. Can you change that?

**Comment by JohnnyX071** [comment]
Could you add that, it is annoying

**Comment by DaPigGuy** [comment]
Set `type` to `command` for the drop to prevent giving items.
