### ISSUE TITLE
Scorehud , Toolbar , Health Bar , Food Bar Has Disappeared When Opening Crate

### ISSUE THREAD

**Issue by BeeAZZ** [DaPigGuy/PiggyCrates#109]
![Uploading Screenshot_20220308-231709.png…]()

**Comment by BeeAZZ** [comment]
![Uploading Screenshot_20220308-231709.png…]()

**Comment by DaPigGuy** [comment]
The [InvCrashFix](https://github.com/Muqsit/InvCrashFix) plugin should fix your issues.
