### ISSUE TITLE
Chests becoming invisible after restart

### ISSUE THREAD

**Issue by Henry12960** [DaPigGuy/PiggyCrates#120]
Hello, I came to report a bug, because the boxes are becoming invisible on the server, I have no idea why, to be sure, I tested it on 2 different hosts and it still continued, you spawn the chest normally, but when you restart the server it becomes transparent /Invisible, hope I helped reporting this.

**Comment by sdsd20021127** [comment]
yes

**Comment by JoshuaPHYT** [comment]
![Screenshot_20220810-200650](https://user-images.githubusercontent.com/69298936/183897212-d47a7d26-75b8-489f-adc9-f74270bba18a.png)
Please fix

**Comment by supercrafter333** [comment]
I can confirm this.

**Comment by JoshuaPHYT** [comment]
Looks like the main dev can't fix it lol. Because he is focusing on dragonfly

**Comment by supercrafter333** [comment]
I'll try to create a PR to fix it in a few weeks.

**Comment by supercrafter333** [comment]
Invalid "bug". Just Update you PocketMine-MP to v4.7.1 or higher and the bug will be fixed.

**Comment by Henry12960** [comment]
Ok, i can test

**Comment by Henry12960** [comment]
Fixed
