### ISSUE TITLE
Drop Enchantment impossible

### ISSUE THREAD

**Issue by Scali3n** [DaPigGuy/PiggyCrates#16]
Hey my first problem is to settle, with my luck there is a second one .. ^^ 'I explain myself: I install PiggyCrate then I configure it but When I test the crate it works but it never drops the item Enchant, so I decided to delete all Drop and put that in the crate common to try and nothing happens, my key disappears and nothing appears in my inventory, cordially ^^

**Comment by Aericio** [comment]
Visit discord server instead.
