### ISSUE TITLE
Question ^^

### ISSUE THREAD

**Issue by Scali3n** [DaPigGuy/PiggyCrates#17]
Is there a plugin that will allow me to use books of enchantment? Let me explain: Your 3 sort of book representing 3 categories: Common Rare Legendary When you type a block with the book it changes into an enchanted book (Paying with EconomyAPI) with a destruction rate and a success rate of enchantment, when you do / merge the book and item fusion or it enchant the item, either destroy the book or destroy the item, or both :) all with piggy enchant thx <3

**Comment by Aericio** [comment]
If you have any more questions, please join our discord instead.
https://discord.gg/ZZewRQH
