### ISSUE TITLE
economyAPI issue with the command feature

### ISSUE THREAD

**Issue by wingsofpaine** [DaPigGuy/PiggyCrates#23]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must not have been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCrates: 1.1.0

- PMMP: PocketMine-MP 1.7dev-999 「[REDACTED]」 implementing API version 3.0.0-ALPHA12 for Minecraft: PE v1.4.0 (protocol version 261)

#### **Steps to Reproduce the Issue**

1. common:
    drops:
      - name: "Stone"
        id: 1
        meta: 0
        amount: 0
        command: givemoney %player% 1000

when you open the crate it doesn't give it to the player the. In the console, it says player not found

**Comment by SalmonDE** [comment]
If I read the code correctly, it must be %PLAYER%.

This is just wrong configuration, so this issue is invalid.

**Comment by wingsofpaine** [comment]
its the same deal either way

**Comment by JackMD** [comment]
Nope its not
