### ISSUE TITLE
/key is broken

### ISSUE THREAD

**Issue by xMatthewRagez11** [DaPigGuy/PiggyCrates#24]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCrates:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
You made two posts of the same issue. Closing this one.
