### ISSUE TITLE
Question: What is the minimum PMMP version needed for PiggyCrates to work?

### ISSUE THREAD

**Issue by DenielWorld** [DaPigGuy/PiggyCrates#32]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCrates:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
It should be compatible with the latest development version (dev#1195)

You're in our Discord. Ask there instead of creating an issue.

**Comment by DenielWorld** [comment]
Check discord

**Comment by Aericio** [comment]
I am on discord, that's why I'm telling you to ask there instead.
