### ISSUE TITLE
chance is not working

### ISSUE THREAD

**Issue by captainleviftw** [DaPigGuy/PiggyCrates#34]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCrates: 1.2.0

- PMMP: PocketMine-MP 3.0.4 for Minecraft: PE v1.4.0 (protocol version 261)

#### **Steps to Reproduce the Issue**

1. Put `chance: 100` on a reward
2. Try opening crate
3. See how you don't often get the reward with 100% chance of getting it

**Comment by DenielWorld** [comment]
From what I tested while using PiggyCrates, it seems to be that the chance doesn't always has to be 1-100. For me it worked with making the max chance 150. Also, it seemed to me that rare items with small chance  had a really small possibility of dropping, so I think this issue is invalid.
