### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Emis02** [DaPigGuy/PiggyCrates#35]
em sorry i placed a chest create a key and it doesn't work can you explain me how it's done?

**Comment by DuooIncc** [comment]
Have you placed the chest on the correct block corresponding to the key you are using?

**Comment by Emis02** [comment]
nope
can you write me a block?

**Comment by DuooIncc** [comment]
Go into your  crates.yml file and then look at the    block: <id>   at the bottom of the rewards and place that block under the chest

**Comment by DuooIncc** [comment]
so if it said     block: 133:0    you would place an emerald block under the chest to make it a crate

**Comment by Emis02** [comment]
wat

**Comment by Emis02** [comment]
ahhhhhhhhhhhh thank you :)

**Comment by Emis02** [comment]
good plugin
