### ISSUE TITLE
/key default permission

### ISSUE THREAD

**Issue by xDanub** [DaPigGuy/PiggyCrates#39]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

This is my first issue report so if I did something wrong please tell me. The permission node piggycrates.command.key seems to not work. /key can be used by default roles and when I plug it into PurePerms as
  - - piggycrates.command.key
It still doesnt disable players to be able to use the /key command.
#### **Version:**

- PiggyCrates: 1.2.0
 
- PMMP: 3.1.1

#### **Steps to Reproduce the Issue**

1. Install the plugin. 
2. Do /key as a default role.

**Comment by DaPigGuy** [comment]
Try this build: https://poggit.pmmp.io/r/38515/PiggyCrates_dev-32.phar
