### ISSUE TITLE
Custom Enchants arent working

### ISSUE THREAD

**Issue by 0pGam3rMC** [DaPigGuy/PiggyCrates#4]
So ive tried custom enchants to my crates and they dont show up but regular vanilla enchants show up.. Is this weird?

**Comment by DaPigGuy** [comment]
Provide your crates.yml

**Comment by 0pGam3rMC** [comment]
legendary:
    drops:
      276:
        name: "Legendary Sword"
        meta: 0
        amount: 1
        enchantments:
          deathbringer:
            level: 1
          sharpness:
            level: 2
          unbreaking:
            level: 1
          Blind:
            level: 1

**Comment by 0pGam3rMC** [comment]
This is not how it looks in my crates.yml just so you know. I did the spacing and everything right.

**Comment by DaPigGuy** [comment]
Make sure you have PiggyCE installed. Join the Discord server here: https://discord.gg/XUHAEWg Aericio can help you

**Comment by Aericio** [comment]
@0pGam3rMC He meant he will help you, sorry for the misunderstanding.

**Comment by 0pGam3rMC** [comment]
Okay. Joined.
