### ISSUE TITLE
Enchanted Books Stack Glitch

### ISSUE THREAD

**Issue by GabbaDaHUt** [DaPigGuy/PiggyCrates#45]
When Receiving the Enchanted Books on Crates it stacks the books when received again

**Comment by Aericio** [comment]
I saw your issue. You don't need to spam issues.

**Comment by GabbaDaHUt** [comment]
sorry i accidently clicked close
but how do you fix it?

**Comment by GabbaDaHUt** [comment]
can yu reply ?

**Comment by Aericio** [comment]
This might have been an issue on the old PiggyCrates, but the rewrite no longer has this issue.
