### ISSUE TITLE
Making New Crates

### ISSUE THREAD

**Issue by EricMelnichuk** [DaPigGuy/PiggyCrates#47]
Quick question, how can i create my own crates? im trying to make a keyall crate that gives everyone random key when used. thanks.

**Comment by ZZWILLIAMXXTrue** [comment]
Hello Eric
To make your own crate follow what you did with the other crates (I copied and paste it) if you want a Key all Crate here is what the reward will look like
     - name: "(CrateName) Keyall"
        id: (whatever is the key for the crates)
        meta: 0
        amount: 0
        chance: (What ever the percent)
        commands:
             - keyall (type) (amount)
