### ISSUE TITLE
Cannot get Custom Enchanted Books to work.

### ISSUE THREAD

**Issue by xDanub** [DaPigGuy/PiggyCrates#48]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCrates
- * [x] Have a detailed title.
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**

I’m not exactly sure why but Enchanted Books won’t keep their enchant. I have PiggyCE set to have the enchantment in the name instead of the lore. I’m not sure which one was supposed to work so I tried this config and none returned an enchanted book.

#### **Version:**
 
- PiggyCrates: 1.4.0
- PiggyCustomEnchants: 1.4.5

- PMMP: 3.9.0

#### **Steps to Reproduce the Issue**

1. Set this as your config:
```  mythic:
    drops:
      - name: "Enchanted Book"
        id: 403
        meta: 0
        amount: 1
        chance: 4
        enchantments:
          Charge:
            level: 1
      - name: "Enchanted Book"
        id: 403
        meta: 0
        amount: 1
        chance: 4
        enchantments:
          charge:
            level: 1
      - name: "Charge I"
        id: 403
        meta: 0
        amount: 1
        chance: 4
        enchantments:
          Charge:
            level: 1
      - name: "Charge I"
        id: 403
        meta: 0
        amount: 1
        chance: 4
        enchantments:
          charge:
            level: 1
    amount: 1
    particle: lava
    delay: 0.25
    block: "57:0" ```
2. Open Mythic crates
#### **Extra Information**
<!-- Anything else we should know? -->

**Comment by xDanub** [comment]
I also have the Custom Enchants on armor pieces that do work, forgot to mention that, sorry.

**Comment by Aericio** [comment]
It should work if you update PiggyCustomEnchants to 1.4.6.

**Comment by xDanub** [comment]
Tysm! Long time no see Aericio! <3
