### ISSUE TITLE
Doesn't works

### ISSUE THREAD

**Issue by creeperplayer20** [DaPigGuy/PiggyCrates#49]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCrates:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

Hi, I have the latest version (dev.2.0.0). I deleted all files of the piggycrates, and added this latest plugin. When I restarted the server and checked the plugins it's red -> piggycrates

**Comment by DaPigGuy** [comment]
Please show any errors that appear in the console

**Comment by creeperplayer20** [comment]
![IMG_20191106_224755](https://user-images.githubusercontent.com/42560781/68340877-89f1ec00-00e7-11ea-87f8-19be4feee742.png)

**Comment by Aericio** [comment]
Check FAQ in readme.

**Comment by DaPigGuy** [comment]
The README of this repository doesn't actually have any information on this. You must install the plugin from Poggit-CI or use DEVirion & use Commando (Not Recommended)

Poggit-CI for PiggyCrates https://poggit.pmmp.io/ci/DaPigGuy/PiggyCrates
