### ISSUE TITLE
Crates are currently un-openable

### ISSUE THREAD

**Issue by J-Scriptware** [DaPigGuy/PiggyCrates#51]
#### **General**

After creating a crate and giving a key to a player, that crate is unable to be opened. Key also disappears from players hand until they re-equip it.
#### **Version:**

- PiggyCrates: 2.0.2

- PMMP: 3.11.1

#### **Steps to Reproduce the Issue**

1. Create a crate and attempt to open using a key.

**Comment by Aericio** [comment]
Please attach your PocketMine-MP.phar, we are unable to reproduce the issue.

**Comment by J-Scriptware** [comment]
Github doesn't allow .phar files to be attached.

**Comment by Aericio** [comment]
Can you put them in a .zip and send it with all 3 inside?

**Comment by J-Scriptware** [comment]
[phar.zip](https://github.com/DaPigGuy/PiggyCrates/files/3999209/phar.zip)

Bisect hosting doesn't allow me to access Pocketmine's .phar but there are the other two.

**Comment by Aericio** [comment]
Did it still work before 3.11.1?

**Comment by J-Scriptware** [comment]
I just created my server a few days ago so the only version of Pocketmine I've used is 3.11.1. And if it helps any the MysteryCrate plugin is also unusable so it might be something to do with the new Pocketmine version.

**Comment by Aericio** [comment]
Yeah, that's what I was thinking. If you could, try using the previous version for now.

**Comment by J-Scriptware** [comment]
Unfortunately I can't roll back the version as my server host won't allow me to, and I believe the previous version is incompatible with 1.14.0 so the Minecraft client wouldn't be able to connect to it.

**Comment by Aericio** [comment]
Well, that sucks :/

Also, 3.11.0 is compatible with 1.14.x. Just not 3.10.x

**Comment by J-Scriptware** [comment]
I contacted support and they allowed custom .phar uploads, and I can confirm that it now works on Pocketmine-MP v3.10.0

**Comment by DaPigGuy** [comment]
Can't seem to reproduce the issue with latest PiggyCrates & PMMP
