### ISSUE TITLE
Missing enchantment examples in crates.yml

### ISSUE THREAD

**Issue by 95CivicSi** [DaPigGuy/PiggyCrates#52]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCrates
- * [x] Have a detailed title.
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**

Default crates.yml should include information on how to add enchantments to items, especially considering that the current method for how this works is different from previous versions.  

This appears to be supported https://github.com/DaPigGuy/PiggyCrates/blob/master/src/DaPigGuy/PiggyCrates/PiggyCrates.php#L64-L67

#### **Version:**

- PiggyCrates: 2.0.2

- PMMP: N/A

**Comment by Aericio** [comment]
It shows in the crappy docs site, but yeah I'll add it here too.
