### ISSUE TITLE
I use Minehub as a server host and when i try to do /crate <crate> it didnt work.You have already setup crates but doesnt work for me when i do /crate.plugin_date is were i try to set it up.

### ISSUE THREAD

**Issue by askaboutarthur** [DaPigGuy/PiggyCrates#58]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title (i.e "Crate items don't appear in inventory")

Link to Crashdump: 

### Extra Information

**Comment by DaPigGuy** [comment]
Please provide more information.
