### ISSUE TITLE
Command in crate

### ISSUE THREAD

**Issue by mikeygio10** [DaPigGuy/PiggyCrates#59]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

Instead of a item you can get a command
### Extra Information
So you could get another key from a crate

**Comment by VoltageMC** [comment]
You can, but you need to make the item amount 0, but this also makes problems with the crate preview, there should be a meta (like with mysterycrates), witch would make it so the player doesnt recive the item, making seeing items like money and spawners possible in the crate preview.

**Comment by DaPigGuy** [comment]
Add under an item `type: command` and it will not give the item.

**Comment by youngjmc** [comment]
Wait how do u do it?

**Comment by Aericio** [comment]
![image](https://user-images.githubusercontent.com/16523741/79421455-88f69d80-7f56-11ea-9058-db68c8d28847.png)
