### ISSUE TITLE
Server  disables piggycrates because of debug

### ISSUE THREAD

**Issue by elimzpvp** [DaPigGuy/PiggyCrates#60]
Im on  the latest on pocketmine and piggycrates 
i just customized my crates and i restart server and this happens everytime
![Capture](https://user-images.githubusercontent.com/63719623/79849092-dd46b680-8376-11ea-9a1c-a8c9073913bf.PNG)

**Comment by DaPigGuy** [comment]
There is something wrong with line 26 of your crates.yml

**Comment by elimzpvp** [comment]
![Capture](https://user-images.githubusercontent.com/63719623/79849447-5514e100-8377-11ea-955f-b2c507caf228.PNG)

this is my line 26. whats wrong with it? im sorry im just new

**Comment by Aericio** [comment]
`name` has to be lined up, so:
```
chance: 15
name: "50k"
type: command
```

**Comment by elimzpvp** [comment]
now it says line 77
![Capture](https://user-images.githubusercontent.com/63719623/79851671-7cb97880-837a-11ea-86a0-8e4b07222f64.PNG)

**Comment by Aericio** [comment]
Send your configuration file

**Comment by elimzpvp** [comment]
crates:
  Common:
    drops:
      - id: 339
        meta: 0
        amount: 1
        chance: 25
        name: "25k"
        type: command
        commands:
          - "givemoney {PLAYER} 25000"
          - "tell {PLAYER} you have recieved 25k"
      - id: 49
        meta: 0
        amount: 32
        chance: 20
    amount: 1
    commands: ["say {PLAYER} has opened an Common Crate"]
    floating-text: "Common Crate"
  Uncommon:
    drops:
      - id: 339
        meta: 0
        amount: 1
        chance: 15
        name: "50k"
        type: command
        commands:
          - "givemoney {PLAYER} 50000"
          - "tell {PLAYER} you have recieved 50k"
      - id: 131
        meta: 0
        amount: 1
        chance: 15
        name: "Mythic Crate Key"
        type: command
        commands:
          - "key mythic {PLAYER} 1"
          - "tell {PLAYER} you have recieved a mythical crate key"
      - id: 92
        meta: 0
        amount: 35
        chance: 75
    amount: 1
    commands: ["say {PLAYER} has opened an Uncommon Crate"]
    floating-text: "Uncommon Crate"
  Vote:
    drops:
      - id: 265
        meta: 0
        amount: 10
        chance: 35
        name: "25k"
        type: command
        commands:
          - "givemoney {PLAYER} 25000"
          - "tell {PLAYER} you have recieved 25k"
      - id: 266
        meta: 0
        amount: 10
        chance: 15
      - id: 17
        meta: 0
        amount: 64
        chance: 50
    amount: 1
    commands: ["say {PLAYER} has opened an Vote Crate"]
    floating-text: "Vote Crate"
  Mythic:
    drops:
      - id: 339
        meta: 0
        amount: 1
        chance: 15
        name: "125k"
        type: command
        commands:
          - "givemoney {PLAYER} 125000"
          - "tell {PLAYER} you have recieved 125k"
      - id: 154
        meta: 0
        amount: 32
        chance: 15
      - id: 276
        meta: 0
        amount: 1
        chance: 10
        name: "Get Oofed On Nub"
        enchantments:
      - name: "Sharpness"
        level: 13
    amount: 1
    commands: ["say {PLAYER} has opened an Mythic Crate"]
    floating-text: "Mythic Crate"
  Legendary:
    drops:
      - id: 311
        meta: 0
        amount: 1
        chance: 10
        name: "Warriors Boob Plate"
        lore: "Might Boob Plate"
        enchantments:
      - name: "Protection"
        level: 14
      - name: "Thorns"
        level: 5
      - name: "Enraged"
        level: 4
      - name: "Gears"
        level: 1
      - id: 339
        meta: 0
        amount: 1
        chance: 25
        name: "500k"
        type: command
        commands:
          - "givemoney {PLAYER} 500000"
          - "tell {PLAYER} you have recieved 500k"
      - id: 57
        meta: 0
        amount: 35
        chance: 65
      - id: 264
        meta: 0
        amount: 1
        chance: 40
        name: "diamond rush"
        type: command
        commands:
          - "give {PLAYER} 264 500"
          - "tell {PLAYER} you have recieved 500 diamonds xd"
    amount: 1
    commands: ["say {PLAYER} has opened an Legendary Crate"]
    floating-text: "Legendary Crate"

**Comment by Aericio** [comment]
Nevermind, paste the contents in here instead: http://www.yamllint.com/
Take a screenshot of the output.

**Comment by elimzpvp** [comment]
![Capture](https://user-images.githubusercontent.com/63719623/79853527-09653600-837d-11ea-930b-393bf951f1a1.PNG)

**Comment by elimzpvp** [comment]
:{

**Comment by Aericio** [comment]
Not sure, line 77 looks correct to me and the website says its valid. 

You might have to re-generate the default file and try again.

**Comment by elimzpvp** [comment]
i might be reading it wrong 
![Capture](https://user-images.githubusercontent.com/63719623/79854941-1c790580-837f-11ea-82ea-e22a86cc8645.PNG)

**Comment by Aericio** [comment]
Yes you are, can you send your configuration **file**? (Upload `crates.yml`)

**Comment by elimzpvp** [comment]
it says you dont support that file type

**Comment by elimzpvp** [comment]
?

**Comment by Aericio** [comment]
I see, go ahead and put it in https://hastebin.com/ instead please.

**Comment by elimzpvp** [comment]
https://hastebin.com/qabevixeca.m

**Comment by elimzpvp** [comment]
done

**Comment by elimzpvp** [comment]
???

**Comment by elimzpvp** [comment]
![Capture](https://user-images.githubusercontent.com/63719623/79907394-5fae9500-83ce-11ea-912d-efc66c9f1637.PNG)

**Comment by pleasepoggitwork** [comment]
;-;

**Comment by elimzpvp** [comment]
hpow can i fix this?

**Comment by elimzpvp** [comment]
?? :{

**Comment by Aericio** [comment]
I'm waiting for hastebin to get back online.

**Comment by elimzpvp** [comment]
hastebin is online please help me fix

**Comment by elimzpvp** [comment]
can i use anything else

**Comment by Aericio** [comment]
https://hasteb.in/

**Comment by elimzpvp** [comment]
https://hasteb.in/fikufeyu.yaml

**Comment by elimzpvp** [comment]
what can i do to fix it

**Comment by DaPigGuy** [comment]
https://hasteb.in/araveded.yaml

**Comment by elimzpvp** [comment]
?

**Comment by elimzpvp** [comment]
![Capture](https://user-images.githubusercontent.com/63719623/79933461-eaaa8200-8404-11ea-9999-89c0803f3c07.PNG)
this is the error
