### ISSUE TITLE
Enchants.

### ISSUE THREAD

**Issue by elimzpvp** [DaPigGuy/PiggyCrates#62]
i fixed the actual crates but now whenever i get the item with enchants out of the crate i get internal server error. this is the error and this is the code thats crashing when i get it.
![Capture](https://user-images.githubusercontent.com/63719623/79940453-9d371080-8416-11ea-833f-192780dcc885.PNG) 
![eee](https://user-images.githubusercontent.com/63719623/79940482-b50e9480-8416-11ea-8ae1-e4917c86d873.PNG)

**Comment by DaPigGuy** [comment]
You're using an extremely outdated version of PiggyCrates.

**Comment by elimzpvp** [comment]
actually im using the latest dev #82 version. most recent one out...... @DaPigGuy

**Comment by DaPigGuy** [comment]
Like I said, this is an extremely outdated version.

* Error occurs on line 137 of the EventListener, while versions 2.0.0+ all have an EventListener file with under 90 lines.
* The class it is trying to find is from PiggyCE v1, and specifically before we changed the namespace. PiggyCrates was updated both times when the PiggyCE namespace was updated & when the PiggyCE v2 error occured.
