### ISSUE TITLE
Preview of crate items {PS4}

### ISSUE THREAD

**Issue by litter295** [DaPigGuy/PiggyCrates#65]
### OS and Versions

* PocketMine-MP: 1.14.6
* PiggyCrates: Latest Version
* PHP: pfft idk

When playstation players attempt to preview the crate items it doesn't work.

### Extra Information

**Comment by Aericio** [comment]
And you didn't use `/reload`?

**Comment by litter295** [comment]
NO

**Comment by litter295** [comment]
Sorry caps*

**Comment by litter295** [comment]
I've used /reload before but realized that it ruins the crate plugin so I no longer use. Does it effect the crates long term? Even after you restart it from the console?

**Comment by Aericio** [comment]
Only doesn't work for the preview? Or does the roulette not work either?

**Comment by litter295** [comment]
Just the preview everything else works fine.

**Comment by Aericio** [comment]
> I've used /reload before but realized that it ruins the crate plugin so I no longer use. Does it effect the crates long term? Even after you restart it from the console?

It won't cause any problems after you restart. `/reload` just tends to break things, like the InvMenu virion.

**Comment by litter295** [comment]
Alright

**Comment by DaPigGuy** [comment]
This seems to be an issue with InvMenu in general on PS4. Similar issue occurred on PiggyAuctions.
