### ISSUE TITLE
Roulette causes client to crash on PocketMine-MP 3.14.0.

### ISSUE THREAD

**Issue by 95CivicSi** [DaPigGuy/PiggyCrates#70]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCrates
- * [x] Have a detailed title.

Link to Crashdump: 

### Extra Information
PocketMine-MP v 3.14.0
PiggyCrates version 2.0.8
When using the roulette option, players attempt to use their keys and are presented the inventory menu as normal.  Once the item has been selected, the player's client is crashed when the inventory window is closed.  I'm not sure yet if this is something missing from PocketMine-MP, but it looks to be related to `Player::removeWindow()`

**Comment by 95CivicSi** [comment]
Related to https://github.com/pmmp/PocketMine-MP/issues/3651

**Comment by provsalt** [comment]
this is a invmenu issue not a piggycrates issue
till the virion is updated, there really isn't any fix for it here

**Comment by Aericio** [comment]
https://github.com/Muqsit/InvMenu/pull/82#issuecomment-653736043

Seems like we'll have to wait for PMMP to fix.

**Comment by Muqsit** [comment]
I pushed some preparatory fixes to InvMenu (^3.1.1 for api3, ^3.2.1 for api4) that i've verified with InvCrashFix plugin until PMMP fixes it.
