### ISSUE TITLE
Sometimes

### ISSUE THREAD

**Issue by xKurt21** [DaPigGuy/PiggyCrates#71]
Hi, 

   When opening a crate chest using the keys, sometimes it is working and sometimes its not. I am using the latest version of this plugin and Pocketmine MP. The Reward was a command "givekit {player} {the kit here}"

Thankyou very much.

**Comment by DaPigGuy** [comment]
What do you mean by "not working"?

**Comment by xKurt21** [comment]
Hi,

When I open the crate chest using the key, sometimes it works and sometimes not (crashed)

**Comment by DaPigGuy** [comment]
#70 The crash is a client issue on 1.16 caused by InvMenu sending the ContainerClosePacket. We can't do much about it
