### ISSUE TITLE
Game crashed when i tried to spin the crates

### ISSUE THREAD

**Issue by DarkVegas** [DaPigGuy/PiggyCrates#73]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.

Link to Crashdump: 

### Extra Information
The plugin works well I can add the crates to the world, I can preview the contents of the crate, I am able to get the keys just fine. However, when I press the crate to start spinning to win something my game crashes completely. I have the latest 1.16 mcpe, I downloaded the latest version of the plugin. I also took all my other plugins out to see if the issue was that a plugin wasn't working with the crates but the same thing happened, my game crashed. In the console it says I logged out from a timeout. 
![Screenshot_20200705-153316_PocketMine-MP](https://user-images.githubusercontent.com/26530964/86535004-2669c980-bed5-11ea-8f34-30dfcd78defe.jpg)
Please help the plugin looks great.

**Comment by minijaham** [comment]
I think it's just your device since it's your minecraft which crashed
