### ISSUE TITLE
Crashing minecraft itself (app closes) on 1.16.1 after opening a crate. The prize is still given.

### ISSUE THREAD

**Issue by justarty** [DaPigGuy/PiggyCrates#74]
Please make sure your issue complies with these guidelines:
- * [PocketMine 3.14.0] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [Havents seen it] Issue must have not been reported previously
- * [2.0.8] Make sure you are on the latest version of PMMP & PiggyCrates
- * [x] Have a detailed title.

Link to Crashdump: 
There are no crash dumps. The minecraft APP is crashing without any worning and server says it's because of timeout.

### Extra Information
You can recreate this by using doing the same thing.

**Comment by DaPigGuy** [comment]
#70

**Comment by Aericio** [comment]
#70
