### ISSUE TITLE
NBT

### ISSUE THREAD

**Issue by SexyLush** [DaPigGuy/PiggyCrates#75]
Ok so I have a plugin that's basically a crates plugin but u cant execute cmds on item drop, so if I wanted someone to get a PiggyCrate key from it it would be impossible, If you can add that or tell me how to, thanks (Discord: SexyLush#6969)

**Comment by Aericio** [comment]
Not our issue. Ask in pmmp discord for plugin development help.

**Comment by SexyLush** [comment]
Bruh what, Im asking how to do NBT.

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyCrates/blob/2be82bf3e3270088f5c89109137f5335cb34aa49/src/DaPigGuy/PiggyCrates/crates/Crate.php#L93

**Comment by SexyLush** [comment]
Can I get an example of how you would write it out in the config?
