### ISSUE TITLE
Crash that disable plugin

### ISSUE THREAD

**Issue by BlackAngels56** [DaPigGuy/PiggyCrates#76]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCrates
- * [x] Have a detailed title.

Link to Crashdump: 
https://hastebin.com/lariqofabo.cs

### Extra Information

**Comment by BlackAngels56** [comment]
I solved but if i use rulete options it kicks me out

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyCrates#notice
