### ISSUE TITLE
why every time I add money and enchant the plugin, the error immediately occurs even though I have followed what you gave :/

### ISSUE THREAD

**Issue by WolFoxHD** [DaPigGuy/PiggyCrates#77]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP:
* PiggyCrates:
* PHP:
* Server OS:

### Extra Information

**Comment by Seeker-Devs** [comment]
You have not filled in some information (actually nothing except the title). Don't expect any help.
