### ISSUE TITLE
A way to get Keys

### ISSUE THREAD

**Issue by WarrenOC** [DaPigGuy/PiggyCrates#85]
A way to get crate keys without /key(all)
I think it would be very nice if you added a way to get keys without the /key and /keyall commands.

### Description
I think it would be very nice if you added a way to get keys without the /key and /keyall commands. It would be very useful and it would help me with my server a ton. This would be like you are mining and suddenly you get a common crate key or maybe you just earned one for killing somebody. I'm not going to tell you how it has to be but I just thought it would be a nice addition.
P.S. If this doesn't make much sense it is my first time using github response things so sorry.

**Comment by Aericio** [comment]
this is out of the scope of this plugin, but isn't hard to make it into your own plugin.
