### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by DragonfireHD** [DaPigGuy/PiggyCrates#86]
I found what from a Player from my server i asked other Devs but he send me to here to send a issue

I hope you can fix that :)

Error line 

return self::$sessions[$player->getRawUniqueId()];

Error: Undefined index: mkiT5וJ0-4
File: plugins/PiggyCrates_dev-102.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/PlayerManager
Line: 45
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PiggyCrates v2.0.9

Code:

Backtrace:
#0 plugins/PiggyCrates_dev-102.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/PlayerManager(45): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[33] Undefined index: mki.T.5..J..0.-4, string[126] phar:///home/minecraft/plugins/PiggyCrates_dev-102.phar/src/DaPigGuy/PiggyCrates, integer 45, array[1])
#1 plugins/PiggyCrates_dev-102.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/inventory/InvMenuInventory(67): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\PlayerManager::getNonNullable(object JackMD\NameSpaceRemover\CustomPlayer)
#2 pmsrc/src/pocketmine/inventory/BaseInventory(412): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory->onClose(object JackMD\NameSpaceRemover\CustomPlayer)
#3 pmsrc/src/pocketmine/Player(4095): pocketmine\inventory\BaseInventory->close(object JackMD\NameSpaceRemover\CustomPlayer)
#4 pmsrc/src/pocketmine/Player(4113): pocketmine\Player->removeWindow(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory, boolean 1)
#5 pmsrc/src/pocketmine/Player(3692): pocketmine\Player->removeAllWindows(boolean 1)
#6 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(176): pocketmine\Player->close(object pocketmine\lang\TranslationContainer, string[21] Internal server error)
#7 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 75.137.213.175 49386, object raklib\protocol\EncapsulatedPacket, integer 0)
#8 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
#9 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
#10

**Comment by Aericio** [comment]
You shouldn't use `/reload`.
