### ISSUE TITLE
Crash to run command

### ISSUE THREAD

**Issue by gabez0** [DaPigGuy/PiggyCrates#87]
PocketMine-MP Crash Dump Tue Jan 12 22:26:08 UTC 2021

Error: Argument 2 passed to pocketmine\Server::dispatchCommand() must be of the type string, array given, called in phar:///home/container/plugins/PiggyCrates (4).phar/src/DaPigGuy/PiggyCrates/tasks/RouletteTask.php on line 86
File: pmsrc/src/pocketmine/Server
Line: 1799
Type: TypeError

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PiggyCrates v2.0.9

**Comment by Aericio** [comment]
most likely messed up config
