### ISSUE TITLE
Players Open Chests

### ISSUE THREAD

**Issue by BlackFire4775** [DaPigGuy/PiggyCrates#91]
So, Players are able to open the chest and just Grab what ever they want out of them now.. Please Help!

**Comment by BlackFire4775** [comment]
You don't understand the Concept of what I said? So there's supposed to be a fake inventory that's created when a player clicks a crate, Correct? And when they click an item it's supposed to NOT stay on their cursor, Correct? And they're NOT supposed to just be able to place the said Item into their inventory, without even needing a key, Right? So- There's a Problem. --- Players on my Server can just take Items out.

**Comment by Aericio** [comment]
I guess you don't understand the concept of filling out an issue template, correct? Fill it out.

What's even more amazing is that you *did* select the bug report template but you completely deleted the template, correct?

I won't spend the time trying to guess your server software, your server software version, your php version, what device you are using, etc.

If you understand that, then you may go ahead and create a new issue, and actually filling out the template this time.
