### ISSUE TITLE
Crates False Inventory Bug

### ISSUE THREAD

**Issue by BlackFire4775** [DaPigGuy/PiggyCrates#92]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCrates
- * [x] Have a detailed title.

### Issue Description
It's probably all the "Changes" Happening with updates/PMMP going into 4.0 --- But 2 Of my players Reported just being able to open the chestto view what they can win, And click the items right into their Inventory, Or simply throw them out onto the ground and can just pick them up ... --- I know who's done it because the "CHANCE" Lore stays on the armor lol. So- Idk how long it's been going on for, But it NEVER did that before *intense forehead sweat* Kinda in the middle of Season 1 for My server & Players all of a sudden just, .. Yknow. LOL. --- So I need Help Figuring out why the Inventory isn't *GLITCHING THE ITEM BACK INTO THE CRATE* when the player clicks it..

- Expected result: What were you expecting to happen?
- I was expecting to open the Crate, Click the Item, And have it return to the crate when I try to drag it Over into my OWN Inv.

- Actual result: What actually happened?
- I was Able To throw Items out of every crate/quick move all items, (THEY ALL STILL HAD "CHANCE" LORE, And everything you'd see when just hovering over the item with mouse)

#### Steps to Reproduce the Issue
1. I HAVE NO CLUE..... --- It's just a False Inventory Bug,
I am Using ---
InvMenu Dev #142 ((I think everything was okay still after I updated the Virion though ..)) But Maybe that IS the problem?
2. I'm Using Piggy's Commando.

### OS and Versions

* PocketMine-MP: Version 3.19.1 Protocol 431
* PiggyCrates: Version 2.0.9
* PHP: /pro/bin/php73/bin/php/pro/bin/mcpe/pocketmine-stable-1.16.220/PocketMine-MP.phar

https://user-images.githubusercontent.com/71064592/117471332-c1806500-af25-11eb-9ce4-8e801a0da4ba.mp4

https://user-images.githubusercontent.com/71064592/117471392-d1984480-af25-11eb-8998-0b77877ff805.mp4

* Server OS:
Windows / Bedrock 1.16.220

### Extra Information
Didn't mean to come across as rude in the other submission, Discouraged, Had to block a lot off /had to clear  ALot.

**Comment by Aericio** [comment]
Unable to reproduce. You might have another plugin conflicting with the menu.
