### ISSUE TITLE
When i open a crate, doesnt let me open the inventory later

### ISSUE THREAD

**Issue by avectss** [DaPigGuy/PiggyCrates#94]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCrates
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP:
* PiggyCrates:
* PHP:
* Server OS:

### Extra Information

**Comment by TurtleSh0ck** [comment]
InvCrashFix

**Comment by Aericio** [comment]
You need to download InvCrashFix: https://poggit.pmmp.io/r/94956/InvCrashFix_dev-3.phar
