### ISSUE TITLE
Login with PiggyCrates and get Internal server errored before loading in the world

### ISSUE THREAD

**Issue by RustlingBrick86** [DaPigGuy/PiggyCrates#96]
Please make sure your issue complies with these guidelines:
- * [ Official PMMP Latest Version] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [I do not believe it has been reported ] Issue must have not been reported previously
- * [ I installed latest PiggyCrates] Make sure you are on the latest version of PMMP & PiggyCrates
- * [Checkmark? ] Have a detailed title.

Link to Crashdump: https://hastebin.com/riwafamawo.yaml

### Extra Information

**Comment by Aericio** [comment]
You shouldn't use `/reload`.
